# Generated by Django 5.1.4 on 2025-11-02 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Base", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="achievement",
            options={"ordering": ["ordinal"]},
        ),
        migrations.AlterModelOptions(
            name="certificate",
            options={"ordering": ["ordinal"]},
        ),
        migrations.AlterModelOptions(
            name="education",
            options={"ordering": ["ordinal"]},
        ),
        migrations.AlterModelOptions(
            name="experience",
            options={"ordering": ["ordinal"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["ordinal"]},
        ),
        migrations.AlterModelOptions(
            name="publication",
            options={"ordering": ["ordinal"]},
        ),
        migrations.RemoveField(
            model_name="achievement",
            name="image",
        ),
        migrations.RemoveField(
            model_name="certificate",
            name="image",
        ),
        migrations.RemoveField(
            model_name="project",
            name="image",
        ),
        migrations.AddField(
            model_name="project",
            name="summary",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="tech_stack",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="PortfolioImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("ordinal", models.IntegerField()),
                ("object_id", models.PositiveIntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["ordinal"],
            },
        ),
    ]
