# Generated by Django 5.1.1 on 2024-09-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_rename_achivement_achievement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='years',
            new_name='duration',
        ),
    ]
