# Generated by Django 5.1.1 on 2024-09-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_rename_years_experience_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='company',
            new_name='issuer',
        ),
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(null=True, upload_to='certificate_images/'),
        ),
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='project_images/'),
        ),
    ]
