# Generated by Django 5.1.1 on 2024-09-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_rename_company_certificate_issuer_certificate_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='duration',
            field=models.CharField(max_length=50),
        ),
    ]
