# Generated by Django 5.1.1 on 2024-09-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_alter_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
